Phase 2 update
frostoven/gamepad-profiler pull request #22
Opened 2023-05-11 14:24 UTC by RebornZA

Please check so work so far. <3

2023-05-12 08:06 UTC, aggregate1166877 requested changes

2023-05-12 08:06 UTC, aggregate1166877 commented on app/react/components/ButtonNamesManager.js
> +const buttonNamesFilePath = path.join(userDataDir, 'button_names.json');
Correct me if I'm wrong, but won't this store your file in `%AppData%/button_names.json`?

2023-05-12 08:06 UTC, aggregate1166877 commented on app/react/components/ButtonNamesManager.js
> +const fs = require('fs');
Please don't mix requires and imports, choose one or the other. This webpack/babel setup is era/server/browser/everything agnostic because it's useful in client/server combo projects and it's therefore not opinionated, but the mixing is bad practice. I suggest you replace this line with `import fs from 'fs';` The file you saw this from has legacy stuff that needs updating.

Also, please place all requires / imports at the top of the document before variable declarations. Placing things further down open you up to hard-to-find bugs further down the line (and is actually expressly forbidden when using imports).

2023-05-12 08:06 UTC, aggregate1166877 commented on app/react/components/ButtonNamesManager.js
> +  if (fs.existsSync(buttonNamesFilePath)) {
Sync functions are only appropriate for server-side scripts. In UI environments, they cause the application to hard-freeze while things are being processed (`Application is Not Responding` kind of stuff). In this exact case things will be especially obvious if the disk is particularly slow or busy.

Your options are:
* Use `fs.exists` with a callback (will require rewriting your code completely, and doesn't work with try/catch so you'll need to rewrite error checking).
* Use the promisified version of `fs.exists` (the code structure should be around 95% the same as it is now).

2023-05-12 08:06 UTC, aggregate1166877 commented on app/react/components/ButtonNamesManager.js
> +      const data = fs.readFileSync(buttonNamesFilePath, 'utf-8');
Just a note on redundancy - seeing as you're checking for literally any error during `fs.readFileSync`, `fs.existsSync` effectively isn't useful here as your `fs.readFileSync` will catch a 'does not exist' error anyway.

2023-05-12 08:06 UTC, aggregate1166877 commented on app/userProfile/index.js
> +export function getUserDataDir() {
Please have a look at the bottom of the file. All exports are defined there. You can declare exports throughout the file, or at the bottom all as one, but not both, because it then makes it difficult to find a pattern in the code logic.

For the sake of consistency, please remove the `export` keyword from here, and add the function name to the exports section at the bottom of the file.

2023-05-12 14:48 UTC, RebornZA commented on app/react/components/ButtonNamesManager.js
> +const buttonNamesFilePath = path.join(userDataDir, 'button_names.json');
AppData/Roaming/button_names.json

2023-05-12 14:57 UTC, RebornZA commented on app/react/components/ButtonNamesManager.js
> +const fs = require('fs');
Noted and correct.

2023-05-12 15:03 UTC, RebornZA commented on app/react/components/ButtonNamesManager.js
> +  if (fs.existsSync(buttonNamesFilePath)) {
Noted. Went for the promisified version.

2023-05-12 15:10 UTC, RebornZA commented on app/userProfile/index.js
> +export function getUserDataDir() {
I did that at first but Webstorm cries.
"Element not exported" even though it is already at the bottom on the file as you described.

2023-05-12 15:50 UTC, RebornZA commented on app/userProfile/index.js
> +export function getUserDataDir() {
Solved it. Was importing it as a named import.

2023-05-15 02:21 UTC, aggregate1166877 commented on app/react/components/ButtonNamesManager.js
> +const buttonNamesFilePath = path.join(userDataDir, 'button_names.json');
![7lsd42](https://github.com/frostoven/gamepad-profiler/assets/5172011/06582818-dedd-4865-bda3-3b6b970ccfc3)

Let's put that in its own directory so as to not clutter the user's system

2023-05-15 12:13 UTC, RebornZA commented
Latest commit:

- Properly waits for directory creation before attempting to read the file.
- Handles gamepad prop potentially being null.
- Waits for asynchronous operations in an orderly manner from a single location.

2023-05-17 13:59 UTC, merged